# Generated by Django 5.0.14 on 2026-06-30 13:24

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(max_length=25)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('student_id', models.CharField(blank=True, max_length=25, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('price', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('month_duration', models.IntegerField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, max_length=10, null=True)),
                ('end_time', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.organization')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('group_id', models.CharField(blank=True, max_length=25, null=True)),
                ('title', models.CharField(max_length=255)),
                ('questions', models.JSONField(default=list)),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='accounts.organization')),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='accounts.organization')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='OrganizationBranch',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.organization')),
            ],
            options={
                'db_table': 'organization_branches',
            },
        ),
        migrations.CreateModel(
            name='OrganizationCourse',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.organization')),
            ],
            options={
                'db_table': 'organization_courses',
            },
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by_id', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='accounts.organization')),
            ],
            options={
                'db_table': 'qr_codes',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('teacher_id', models.CharField(blank=True, max_length=25, null=True)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('time_start', models.CharField(max_length=10)),
                ('time_end', models.CharField(max_length=10)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='accounts.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='accounts.organization')),
            ],
            options={
                'db_table': 'schedule_entries',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_ids', models.JSONField(default=list)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('debt', 'Debt'), ('risk', 'Risk')], default='debt', max_length=10)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('risk_group', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.organization')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group_id', models.CharField(blank=True, max_length=25, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField()),
                ('method', models.CharField(choices=[('Naqd', 'Naqd'), ('Click', 'Click'), ('Payme', 'Payme'), ('Uzum', 'Uzum'), ('Bank', 'Bank'), ('Stripe', 'Stripe')], default='Naqd', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=25, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.organization')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.student')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('created_by_id', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.student')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('completion', 'Completion'), ('participation', 'Participation'), ('achievement', 'Achievement')], default='completion', max_length=20)),
                ('certificate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('issued_by_id', models.CharField(blank=True, max_length=25, null=True)),
                ('issued_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.organization')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='accounts.student')),
            ],
            options={
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('marked_by_id', models.CharField(blank=True, max_length=25, null=True)),
                ('marked_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.student')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(auto_now_add=True)),
                ('current_period_end', models.DateTimeField()),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payme_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.organization')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('org_admin', 'Org Admin'), ('manager', 'Manager'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
                ('two_factor_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('refresh_token', models.TextField(blank=True, null=True, unique=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.user')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'otp_codes',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.user')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('student_id', models.CharField(blank=True, max_length=25, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.organization')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='accounts.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.user')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_groups', to='accounts.user'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.user')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('type', models.CharField(default='general', max_length=50)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.user')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('student_id', models.CharField(blank=True, max_length=25, null=True)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('answers', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.exam')),
            ],
            options={
                'db_table': 'exam_results',
                'indexes': [models.Index(fields=['exam'], name='exam_result_exam_id_14ebd6_idx'), models.Index(fields=['student_id'], name='exam_result_student_836d1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('files', models.JSONField(default=list)),
                ('created_by_id', models.CharField(blank=True, max_length=25, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='accounts.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='accounts.organization')),
            ],
            options={
                'db_table': 'homework',
                'indexes': [models.Index(fields=['organization', 'group'], name='homework_organiz_924944_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.CharField(blank=True, max_length=25, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.organization')),
            ],
            options={
                'db_table': 'expenses',
                'indexes': [models.Index(fields=['organization', 'date'], name='expenses_organiz_7ef573_idx'), models.Index(fields=['organization', 'category'], name='expenses_organiz_4543a3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['organization', 'group_id'], name='exams_organiz_31131c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['organization', 'category'], name='books_organiz_773943_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationbranch',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationcourse',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['organization', 'code'], name='qr_codes_organiz_d4f7a8_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleentry',
            index=models.Index(fields=['organization', 'group', 'day'], name='schedule_en_organiz_77733f_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'group'], name='students_organiz_1bb6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'phone'], name='students_organiz_728a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'student'], name='payments_organiz_59ebd3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'date'], name='payments_organiz_849373_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['organization', 'student'], name='grades_organiz_e5b42a_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['organization', 'subject'], name='grades_organiz_f6f11c_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['organization', 'student'], name='certificate_organiz_2dd8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['organization', 'date'], name='attendance_organiz_104948_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('organization', 'student', 'date')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role'], name='users_organiz_6045b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('organization', 'email'), ('organization', 'login')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user'], name='sessions_user_id_7acd24_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['expires_at'], name='sessions_expires_bbb852_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['phone', 'code', 'type'], name='otp_codes_phone_2ee03d_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['email', 'code', 'type'], name='otp_codes_email_d496e5_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['expires_at'], name='otp_codes_expires_348c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'user'], name='notificatio_organiz_ff86a0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'read'], name='notificatio_organiz_046533_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organization', 'sender', 'receiver'], name='messages_organiz_45dbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organization', 'created_at'], name='messages_organiz_3e75a0_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['organization', 'teacher'], name='groups_organiz_c94c51_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['organization', 'user'], name='devices_organiz_817fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'type'], name='audit_logs_organiz_71cc30_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'created_at'], name='audit_logs_organiz_af0d8d_idx'),
        ),
    ]
