from django.urls import path, include

urlpatterns = [
    path('api/auth/', include('apps.accounts.urls')),
    path('api/organizations/', include('apps.accounts.org_urls')),
    path('api/users/', include('apps.accounts.user_urls')),
    path('api/groups/', include('apps.groups.urls')),
    path('api/students/', include('apps.students.urls')),
    path('api/payments/', include('apps.payments.urls')),
    path('api/expenses/', include('apps.expenses.urls')),
    path('api/attendance/', include('apps.attendance.urls')),
    path('api/homework/', include('apps.homework.urls')),
    path('api/grades/', include('apps.grades.urls')),
    path('api/schedule/', include('apps.schedule.urls')),
    path('api/library/', include('apps.library.urls')),
    path('api/exams/', include('apps.exams.urls')),
    path('api/certificates/', include('apps.certificates.urls')),
    path('api/notifications/', include('apps.notifications.urls')),
    path('api/messages/', include('apps.messages.urls')),
    path('api/dashboard/', include('apps.dashboard.urls')),
    path('api/reports/', include('apps.reports.urls')),
    path('api/audit-logs/', include('apps.audit.urls')),
    path('api/teachers/', include('apps.teacher.urls')),
    path('api/parent/', include('apps.parent.urls')),
    path('api/settings/', include('apps.setting.urls')),
    path('api/email/', include('apps.email.urls')),
    path('api/fcm/', include('apps.fcm.urls')),
    path('api/payments/providers/', include('apps.payment_provider.urls')),
    path('api/health/', include('apps.health.urls')),
    path('api/docs/', include('apps.docs.urls')),
]
